version: '3.7'
services:
  health-services-db:
    image: postgres
    restart: always
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: healthsvcs
      POSTGRES_PASSWORD: healthsvcs
      ANON: web_anon
      AUTHENTICATOR: authenticator


volumes:
  db-data:
    driver: local