version: '3.7'
services:
  account-services-db:
    image: postgres
    restart: always
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
      ANON: web_anon
      AUTHENTICATOR: authenticator
  account-services:
    depends_on:
      - account-services-db
    image: org.myhealthtrax/accountservices
    restart: always
    ports:
      - 8080:8080
    environment:
      JDBC_URL: jdbc:postgresql://account-services-db:5432/accounts

volumes:
  db-data:
    driver: local